V1
Kevin-Spring/generation_book_plugin pull request #1
Opened 2020-12-09 08:27 UTC by Kevin-Spring

2020-12-09 09:04 UTC, hmstrandberg requested changes
Tycker det är grymt att du delat upp all funktionalitet i egna filer. Syntaxen ser generellt bra ut, har lagt in ett par kommentarer om syntaxen men du får gärna kolla igenom och se till att det görs i samtliga filer. 

Om du vill göra det ännu snyggare skulle du kunna göra det objektorienterat. Dvs göra classer av alla filer. Säg till om du vill att vi går igenom hur det funkar :)

2020-12-09 09:04 UTC, hmstrandberg commented on generation-book-feed-shortcode.php
> +
Kolla igenom och se till att köra passande esc-funktioner på allting du skriver ut i html:en :)

2020-12-09 09:04 UTC, hmstrandberg commented on generation-book-feed-shortcode.php
> +                echo '<p> Författare: <b>' . esc_html( get_post_meta( get_the_ID(), 'author' )[0] ) . '</b></p>';
På alla get_post_meta-funktioner så får du nu en array. Om du lägger till en tredje parameter true så får du tillbaka svaret som en sträng istället: get_post_meta( get_the_ID(), 'author', true );

2020-12-09 09:04 UTC, hmstrandberg commented on generation-book-feed-shortcode.php
> +    $content = ob_get_clean();
Här kan du köra return ob_get_clean(); direkt bara istället för att lägga det i en variabel

2020-12-09 09:04 UTC, hmstrandberg commented on generation-book-feed-shortcode.php
> +
Ta bort tomma rader

2020-12-09 09:04 UTC, hmstrandberg commented on generation-book-feed.php
> +
Ta bort tomma rader

2020-12-11 09:13 UTC, Kevin-Spring commented on generation-book-feed-post-type.php
> +    $args = [
'publicly_queryable'    => false, kanske? :)

2020-12-11 09:14 UTC, Kevin-Spring commented on generation-book-feed-post-type.php
> +    $args = [
Lägga in 'menu_icon' => url, bland mina $args?

2020-12-11 09:48 UTC, hmstrandberg commented on generation-book-feed-post-type.php
> +    $args = [
yes menu_icon är rätt och sen kan du skriva in sluggen till en såkallad dashicon, finns här: https://developer.wordpress.org/resource/dashicons

2020-12-11 09:52 UTC, hmstrandberg commented on generation-book-feed-post-type.php
> +    $args = [
yes det är ett steg påvägen, men man behöver även ställa om lite andra parametrar för att det ska fungera fullt ut:
```
'public'             => false,
'has_archive'        => false,
'publicly_queryable' => false,
'rewrite'            => false,
'show_in_nav_menus'  => true,
'show_ui'            => true,
```

2020-12-11 10:15 UTC, merged